server:
  port: 3030

mywx:
  appID: 测试号appid
  appsecret: 自己设置
  #天气模板id
  tempateid1: 天气模板id
  #时间模板id
  tempateid2: 时间模板id
  #事件提醒
  tempateid3: 事件提醒模板id
  #城市id，这个id自己去网上找对应的城市id。https://yikeapi.com/help/tianqicity
  cityid:
  #认识的日子
  day1:
  #在一起的日子
  day2: 
  #我的生日
  day3:
  #宝贝生日
  day4:
  #要推送的用户列表
  users:
    - 用户id1
    - 用户id2
